config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "staff_constraint"

Rails.application.routes.draw do
  mount Peek::Railtie => "/peek"

  root to: "pages#home"

  get  "/login",  to: "sessions#new",     as: "login"
  post "/logout", to: "sessions#destroy", as: "logout"

  match "/auth/:provider/callback", to: "sessions#create",  via: %i[get post]
  match "/auth/failure",            to: "sessions#failure", via: %i[get post]

  get "/a/:short_key", to: "short_url#assignment_invitation",       as: "assignment_invitation_short"
  get "/g/:short_key", to: "short_url#group_assignment_invitation", as: "group_assignment_invitation_short"

  get "/autocomplete/github_repos", to: "autocomplete#github_repos"

  get "/boom", to: "site#boom_town"
  get "/boom/sidekiq", to: "site#boom_sidekiq"

  scope "github", as: "github" do
    constraints user_agent: %r{\AGitHub-Hookshot/\w+\z}, format: "json" do
      post :hooks, to: "hooks#receive"
    end
  end

  resources :assignment_invitations, path: "assignment-invitations", only: [:show] do
    member do
      patch :accept
      get   :setup
      patch :setup_progress
      get   :success
      patch :join_roster
    end
  end

  resources :group_assignment_invitations, path: "group-assignment-invitations", only: [:show] do
    member do
      get   :accept
      patch :accept_assignment
      patch :accept_invitation
      get   :setup
      patch :setup_progress
      get   :successful_invitation, path: :success
      patch :join_roster
    end
  end

  scope path_names: { edit: "settings" } do
    resources :organizations, path: "classrooms" do
      member do
        get   :invite
        get   :new_assignment, path: "new-assignment"
        get   :setup
        patch :setup_organization
        get   "settings/invitations", to: "organizations#invitation"
        get   "settings/teams",       to: "organizations#show_groupings"
        delete "users/:user_id",      to: "organizations#remove_user", as: "remove_user"

        resource :roster, only: %i[show new create], controller: "orgs/rosters" do
          patch :link
          patch :unlink
          patch :delete_entry
          patch :add_student
          patch :remove_organization
        end
      end

      resources :groupings, only: %i[show edit update] do
        resources :groups, only: [:show] do
          member do
            patch "/memberships/:user_id", to: "groups#add_membership", as: "add_membership"
            delete "/memberships/:user_id", to: "groups#remove_membership", as: "remove_membership"
          end
        end
      end

      resources :assignments do
        resources :assignment_repos, only: [:show], controller: "orgs/assignment_repos"
        get "/roster_entries/:roster_entry_id", to: "orgs/roster_entries#show", as: "roster_entry"
      end

      resources :group_assignments, path: "group-assignments" do
        resources :group_assignment_repos, only: [:show], controller: "orgs/group_assignment_repos"
        get "/roster_entries/:roster_entry_id", to: "orgs/roster_entries#show", as: "roster_entry"
      end
    end
  end

  resources :videos, only: [:index]

  namespace :stafftools do
    constraints StaffConstraint.new do
      mount Sidekiq::Web => "/sidekiq"
      mount Flipper::UI.app(GitHubClassroom.flipper) => "/flipper", as: "flipper"
    end

    root "resources#index", as: :root
    get "/resource_search", to: "resources#search"

    resources :users, only: [:show] do
      member do
        post :impersonate
        delete :stop_impersonating
      end
    end

    resources :organizations, path: "classrooms", only: [:show] do
      member do
        delete "/users/:user_id", to: "organizations#remove_user", as: "remove_user"
      end
    end

    resources :repo_accesses, only: [:show]

    resources :assignment_invitations, only: [:show]
    resources :assignment_repos,       only: %i[show destroy]
    resources :assignments,            only: [:show]

    resources :deadlines, only: [:show]

    resources :group_assignment_invitations, path: "group-assignment-invitations", only: [:show]
    resources :group_assignment_repos,       path: "group-assignment-repos",       only: %i[show destroy]
    resources :group_assignments,            path: "group-assignments",            only: [:show]

    resources :groupings, only: [:show]
    resources :groups,    only: [:show]
  end
end

app/views/shared/_commit_repo_detail.html.erb
<%= render 'shared/repo_detail',
  octicon_name: 'git-commit',
  octicon_class: 'neutral',
  text: text,
  hover_text: 'View commits',
  url: url %>

app/views/shared/_failed_repo_detail.html.erb
<%= render 'shared/repo_detail',
  octicon_name: 'x',
  octicon_class: 'failed',
  text: text
%>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="flash-application container-lg">
    <%= content_tag :div, class: "flash #{primer_class_for(type)}" do %>
      <span class="flash-close js-flash-close">
        <%= octicon('x') %>
      </span>
      <%= sanitize(message) %>
    <% end %>
  </div>
<% end %>

app/views/shared/_form_error.html.erb
  <dd class="error"><%= errors %></dd>

app/views/shared/_header.html.erb
<header class="site-header">
  <div class="container-lg clearfix">
    <%= link_to(image_tag('logo@2x.png', class: 'site-logo', alt: 'GitHub for Classrooms'), (logged_in? ? organizations_path : root_path)) %>

    <nav class="site-nav float-right  d-flex flex-wrap flex-content-start flex-justify-center">
      <%= link_to "GitHub Education", 'https://education.github.com', target: '_blank' %>

      <ul>
        <% if logged_in? %>
          <li>
            <%= link_to 'https://education.github.com/forum', class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.community_discussion') do %>
              <%= octicon 'comment-discussion' %>
            <% end %>
          </li>

          <li>
            <%= link_to videos_path, class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.video_tutorials') do %>
              <%= octicon 'device-camera-video' %>
            <% end %>
          </li>

          <li>
            <%= link_to 'https://github.com/education/classroom/issues/new?labels[]=report', class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.report_bug') do %>
              <%= octicon 'bug' %>
            <% end %>
          </li>

          <li>
            <%= link_to 'https://github.com/education/classroom/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc', target: '_blank', class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.changelog') do %>
              <%= octicon 'git-pull-request' %>
            <% end %>
          </li>

          <li>
            <% if impersonating?(current_user, true_user) %>
              <%= link_to stop_impersonating_stafftools_user_path(current_user), class: 'tooltipped tooltipped-s', method: :delete, 'aria-label' => t('views.shared.stop_impersonating', user: current_user.github_user.login) do %>
                <div class="avatar-parent-child left">
                  <%= image_tag current_user.github_user.github_avatar_url(40), class: 'avatar', alt: "@#{current_user.github_user.login}", height: 20, width: 20 %>
                  <%= image_tag true_user.github_user.github_avatar_url(20), class: 'avatar avatar-child', alt: "@#{true_user.github_user.login}", height: 10, width: 10 %>
                </div>
              <% end %>
            <% else %>
              <%= link_to current_user.github_user.html_url, class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.view_gh_profile') do %>
                <%= image_tag current_user.github_user.github_avatar_url(40), class: 'avatar', alt: "@#{current_user.github_user.login}", height: 20, width: 20 %>
              <% end %>
            <% end %>
          </li>

          <li>
            <%= link_to logout_path, method: :post, class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.sign_out') do %>
              <%= octicon 'sign-out' %>
            <% end %>
          </li>

        <% else %>
          <li><%= link_to t('views.shared.sign_in'), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<% if controller_path.split('/').first == 'stafftools' %>
  <div class="stafftools-border"></div>
<% end %>

app/views/shared/_invitation.html.erb
<form>
  <% if mobile? %>
    <%= render partial: "shared/invitations/mobile", locals: local_assigns %>
  <% else %>
    <%# if for some reason the user has a really tiny desktop screen fallback to the mobile view" %>
    <%= render partial: "shared/invitations/mobile", locals: local_assigns %>
    <%= render partial: "shared/invitations/desktop", locals: local_assigns %>
  <% end %>
</form>

app/views/shared/_invitation_header.html.erb
<header class="site-header">
  <div class="container-lg">
    <%= image_tag('logo@2x.png', :class => 'site-logo', :alt => 'GitHub for Classrooms') %>

    <nav class="site-nav">
      <ul>
        <li>
          <%= link_to "GitHub Education", 'https://education.github.com', target: '_blank' %>
        </li>

        <li>
          <%= link_to 'https://education.github.com/forum', class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.community_discussion') do %>
            <%= octicon 'comment-discussion' %>
          <% end %>
        </li>

        <li>
          <%= link_to videos_path, class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.video_tutorials') do %>
            <%= octicon 'device-camera-video' %>
          <% end %>
        </li>

        <li>
          <%= link_to 'https://github.com/education/classroom/issues/new', class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.report_bug') do %>
            <%= octicon 'bug' %>
          <% end %>
        </li>

        <li>
          <%= link_to 'https://github.com/education/classroom/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc', target: '_blank', class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.changelog') do %>
            <%= octicon 'git-pull-request' %>
          <% end %>
        </li>

        <li>
          <%= link_to current_user.github_user.html_url, class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.view_gh_profile') do %>
            <%= image_tag current_user.github_user.github_avatar_url(40), class: 'avatar', alt: "@#{current_user.github_user.login}", height: 20, width: 20 %>
          <% end %>
        </li>

        <li>
          <%= link_to logout_path, method: :post, class: 'tooltipped tooltipped-s', 'aria-label' => t('views.shared.sign_out') do %>
            <%= octicon 'sign-out' %>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_members_repo_detail.html.erb
<%= render 'shared/repo_detail',
  octicon_name: 'person',
  octicon_class: 'neutral',
  text: text,
  hover_text: 'View members',
  url: url %>

app/views/shared/_pagination.html.erb
<% if collection.next_page || collection.prev_page %>
  <div class="paginate-container container">
    <%= paginate collection, param_name: (local_assigns[:param_name] || :page) %>
  </div>
<% end %>

app/views/shared/_repo_detail.html.erb
<% # optional params    %>
<% url           ||= '' %>
<% hover_text    ||= '' %>

<% if url.present? %>
  <a class="repo-detail-item <%= 'tooltipped tooltipped-n' if hover_text.present? %>" aria-label="<%= hover_text %>" href="<%= url %>" target='_blank'>
    <span class="submission-icon-container">
      <%= octicon octicon_name, height: 20, class: octicon_class %>
    </span>
    <span class='text-muted'><%= text %></span>
  </a>
<% else %>
    <span class="repo-detail-item <%= 'tooltipped tooltipped-n' if hover_text.present? %>" aria-label="<%= hover_text %>">
      <span class='submission-icon-container'>
        <%= octicon octicon_name, height: 20, class: octicon_class %>
      </span>
      <span class='text-muted'><%= text %></span>
    </span>
<% end %>

app/views/shared/_roster_tab_script.html.erb
<script>
  if(typeof selectTab === "function"){
    setTabOnLoad();
  }else{
    document.addEventListener("DOMContentLoaded", function(_event) {
      setTabOnLoad();
    });
  }
</script>

app/views/shared/_submission_failed_repo_detail.html.erb
<%= render 'shared/repo_detail',
  octicon_name: 'stop',
  octicon_class: 'failed',
  text: 'Not Submitted' %>

app/views/shared/_unlimited_free_private_repositories_banner.html.erb
<div class="one-third column  Box box-shadow bordered  p-3" >
  <p class="text-emphasized">Unlimited free private repositories</p>
  <p class="text-gray">If you have not already, you may apply for unlimited free private repositories for this classroom organization <a href="https://education.github.com/discount_requests/new">here</a>.</p>
</div>

app/views/shared/_unlinked_blank_slate.html.erb
<div class="blankslate">
  <h3><%= t("views.rosters.blank_slate_header") %></h3>
</div>