config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "staff_constraint"

Rails.application.routes.draw do
  mount Peek::Railtie => "/peek"

  root to: "pages#home"

  get  "/login",  to: "sessions#new",     as: "login"
  post "/logout", to: "sessions#destroy", as: "logout"

  match "/auth/:provider/callback", to: "sessions#create",  via: %i[get post]
  match "/auth/failure",            to: "sessions#failure", via: %i[get post]

  get "/a/:short_key", to: "short_url#assignment_invitation",       as: "assignment_invitation_short"
  get "/g/:short_key", to: "short_url#group_assignment_invitation", as: "group_assignment_invitation_short"

  get "/autocomplete/github_repos", to: "autocomplete#github_repos"

  get "/boom", to: "site#boom_town"
  get "/boom/sidekiq", to: "site#boom_sidekiq"

  scope "github", as: "github" do
    constraints user_agent: %r{\AGitHub-Hookshot/\w+\z}, format: "json" do
      post :hooks, to: "hooks#receive"
    end
  end

  resources :assignment_invitations, path: "assignment-invitations", only: [:show] do
    member do
      patch :accept
      get   :setup
      patch :setup_progress
      get   :success
      patch :join_roster
    end
  end

  resources :group_assignment_invitations, path: "group-assignment-invitations", only: [:show] do
    member do
      get   :accept
      patch :accept_assignment
      patch :accept_invitation
      get   :setup
      patch :setup_progress
      get   :successful_invitation, path: :success
      patch :join_roster
    end
  end

  scope path_names: { edit: "settings" } do
    resources :organizations, path: "classrooms" do
      member do
        get   :invite
        get   :new_assignment, path: "new-assignment"
        get   :setup
        patch :setup_organization
        get   "settings/invitations", to: "organizations#invitation"
        get   "settings/teams",       to: "organizations#show_groupings"
        delete "users/:user_id",      to: "organizations#remove_user", as: "remove_user"

        resource :roster, only: %i[show new create], controller: "orgs/rosters" do
          patch :link
          patch :unlink
          patch :delete_entry
          patch :add_student
          patch :remove_organization
        end
      end

      resources :groupings, only: %i[show edit update] do
        resources :groups, only: [:show] do
          member do
            patch "/memberships/:user_id", to: "groups#add_membership", as: "add_membership"
            delete "/memberships/:user_id", to: "groups#remove_membership", as: "remove_membership"
          end
        end
      end

      resources :assignments do
        resources :assignment_repos, only: [:show], controller: "orgs/assignment_repos"
        get "/roster_entries/:roster_entry_id", to: "orgs/roster_entries#show", as: "roster_entry"
      end

      resources :group_assignments, path: "group-assignments" do
        resources :group_assignment_repos, only: [:show], controller: "orgs/group_assignment_repos"
        get "/roster_entries/:roster_entry_id", to: "orgs/roster_entries#show", as: "roster_entry"
      end
    end
  end

  resources :videos, only: [:index]

  namespace :stafftools do
    constraints StaffConstraint.new do
      mount Sidekiq::Web => "/sidekiq"
      mount Flipper::UI.app(GitHubClassroom.flipper) => "/flipper", as: "flipper"
    end

    root "resources#index", as: :root
    get "/resource_search", to: "resources#search"

    resources :users, only: [:show] do
      member do
        post :impersonate
        delete :stop_impersonating
      end
    end

    resources :organizations, path: "classrooms", only: [:show] do
      member do
        delete "/users/:user_id", to: "organizations#remove_user", as: "remove_user"
      end
    end

    resources :repo_accesses, only: [:show]

    resources :assignment_invitations, only: [:show]
    resources :assignment_repos,       only: %i[show destroy]
    resources :assignments,            only: [:show]

    resources :deadlines, only: [:show]

    resources :group_assignment_invitations, path: "group-assignment-invitations", only: [:show]
    resources :group_assignment_repos,       path: "group-assignment-repos",       only: %i[show destroy]
    resources :group_assignments,            path: "group-assignments",            only: [:show]

    resources :groupings, only: [:show]
    resources :groups,    only: [:show]
  end
end

app/models/group_assignment_repo.rb
# frozen_string_literal: true

class GroupAssignmentRepo < ApplicationRecord
  include GitHubPlan
  include GitHubRepoable
  include Nameable

  update_index("stafftools#group_assignment_repo") { self }

  enum configuration_state: %i[not_configured configuring configured]

  belongs_to :group
  belongs_to :group_assignment
  alias assignment group_assignment

  has_one :organization, -> { unscope(where: :deleted_at) }, through: :group_assignment

  has_many :repo_accesses, through: :group

  validates :github_repo_id, presence:   true
  validates :github_repo_id, uniqueness: true

  validates :group_assignment, presence: true

  validates :group, presence: true
  validates :group, uniqueness: { scope: :group_assignment }

  before_validation(on: :create) do
    if organization
      create_github_repository
      push_starter_code
      add_team_to_github_repository
    end
  end

  before_destroy :silently_destroy_github_repository

  delegate :creator, :starter_code_repo_id, to: :group_assignment
  delegate :github_team_id,                 to: :group
  delegate :default_branch, :commits,       to: :github_repository

  # TODO: Move to a view model
  def disabled?
    @disabled ||= !github_repository.on_github? || !github_team.on_github?
  end

  def github_repository
    @github_repository ||= GitHubRepository.new(organization.github_client, github_repo_id)
  end

  def github_team
    @github_team ||= group.github_team
  end

  def private?
    !group_assignment.public_repo?
  end

  def repo_name
    @repo_name ||= generate_github_repo_name
  end

  def import_status
    return "No starter code provided" unless group_assignment.starter_code?

    github_repository.import_progress.status.humanize
  end

  private

  delegate :slug, to: :group_assignment

  def name
    @name ||= group.github_team.slug_no_cache
  end
end

app/controllers/orgs/group_assignment_repos_controller.rb
# frozen_string_literal: true

module Orgs
  class GroupAssignmentReposController < Orgs::Controller
    layout false

    def show
      @group_assignment_repo = GroupAssignmentRepo.includes(:group).find_by!(
        id: params[:id],
        group_assignment: current_group_assignment
      )
    end

    private

    def current_group_assignment
      return @current_assignment if defined?(@current_assignment)
      @current_assignment = current_organization.group_assignments.find_by(slug: params[:group_assignment_id])
    end
  end
end

app/controllers/stafftools/assignment_invitations_controller.rb
# frozen_string_literal: true

module Stafftools
  class AssignmentInvitationsController < StafftoolsController
    before_action :set_assignment_invitation

    def show; end

    private

    def set_assignment_invitation
      @assignment_invitation = AssignmentInvitation.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/assignment_repos_controller.rb
# frozen_string_literal: true

module Stafftools
  class AssignmentReposController < StafftoolsController
    before_action :set_assignment_repo

    def show; end

    def destroy
      assignment = @assignment_repo.assignment

      if @assignment_repo.destroy
        flash[:success] = "Assignment repository was destroyed"
        redirect_to stafftools_assignment_path(assignment.id)
      else
        flash[:error] = "Could not delete assignment repository"
        render :show
      end
    end

    private

    def set_assignment_repo
      @assignment_repo = AssignmentRepo.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/assignments_controller.rb
# frozen_string_literal: true

module Stafftools
  class AssignmentsController < StafftoolsController
    before_action :set_assignment

    def show; end

    private

    def set_assignment
      @assignment = Assignment.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/deadlines_controller.rb
# frozen_string_literal: true

module Stafftools
  class DeadlinesController < StafftoolsController
    before_action :set_deadline

    def show; end

    private

    def set_deadline
      @deadline = Deadline.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/group_assignment_invitations_controller.rb
# frozen_string_literal: true

module Stafftools
  class GroupAssignmentInvitationsController < StafftoolsController
    before_action :set_group_assignment_invitation

    def show; end

    private

    def set_group_assignment_invitation
      @group_assignment_invitation = GroupAssignmentInvitation.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/group_assignment_repos_controller.rb
# frozen_string_literal: true

module Stafftools
  class GroupAssignmentReposController < StafftoolsController
    before_action :set_group_assignment_repo

    def show; end

    def destroy
      group_assignment = @group_assignment_repo.group_assignment

      if @group_assignment_repo.destroy
        flash[:success] = "Group assignment repository was destroyed"
        redirect_to stafftools_group_assignment_path(group_assignment.id)
      else
        flash[:error] = "Could not delete group assignment repository"
        render :show
      end
    end

    private

    def set_group_assignment_repo
      @group_assignment_repo = GroupAssignmentRepo.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/group_assignments_controller.rb
# frozen_string_literal: true

module Stafftools
  class GroupAssignmentsController < StafftoolsController
    before_action :set_group_assignment

    def show; end

    private

    def set_group_assignment
      @group_assignment = GroupAssignment.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/groupings_controller.rb
# frozen_string_literal: true

module Stafftools
  class GroupingsController < StafftoolsController
    before_action :set_grouping

    def show; end

    private

    def set_grouping
      @grouping = Grouping.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/groups_controller.rb
# frozen_string_literal: true

module Stafftools
  class GroupsController < StafftoolsController
    before_action :set_group

    def show; end

    private

    def set_group
      @group = Group.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/organizations_controller.rb
# frozen_string_literal: true

module Stafftools
  class OrganizationsController < StafftoolsController
    before_action :set_organization

    def show; end

    def remove_user
      user = User.find(params[:user_id])

      if Assignment.find_by(creator: user).present?
        flash[:error] = "This user owns at least one assignment and cannot be deleted"
      else
        @organization.users.delete(user)
        flash[:success] = "The user has been removed from the classroom"
      end

      redirect_to stafftools_organization_path(@organization.id)
    end

    private

    def set_organization
      @organization = Organization.includes(:users).find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/repo_accesses_controller.rb
# frozen_string_literal: true

module Stafftools
  class RepoAccessesController < StafftoolsController
    before_action :set_repo_access

    def show; end

    private

    def set_repo_access
      @repo_access = RepoAccess.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/resources_controller.rb
# frozen_string_literal: true

module Stafftools
  class ResourcesController < StafftoolsController
    before_action :set_resources

    def index; end

    def search
      respond_to do |format|
        format.html { render partial: "stafftools/resources/search_results", locals: { resources: @resources } }
      end
    end

    private

    def set_resources
      return @resources = nil if params[:query].blank?
      @resources = StafftoolsIndex
                   .query(match_phrase_prefix(params[:query]))
                   .order(_type: :asc)
                   .page(params[:page])
                   .per(20)
    end

    def match_phrase_prefix(query)
      searchable_fields = %w[github_id github_repo_id github_team_id id key login name slug title uid]
      { bool: { should: searchable_fields.map { |field| { "match_phrase_prefix" => { field => query } } } } }
    end
  end
end

app/controllers/stafftools/users_controller.rb
# frozen_string_literal: true

module Stafftools
  class UsersController < StafftoolsController
    skip_before_action :authorize_access, only: [:stop_impersonating]

    before_action :set_user, except: [:stop_impersonating]

    def show; end

    def impersonate
      session[:impersonated_user_id] = @user.id
      redirect_to root_path
    end

    def stop_impersonating
      not_found unless true_user.try(:staff?)

      session.delete(:impersonated_user_id)
      redirect_to stafftools_root_path
    end

    private

    def set_user
      @user = User.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools_controller.rb
# frozen_string_literal: true

class StafftoolsController < ApplicationController
  layout "stafftools"

  before_action :authorize_access

  private

  def authorize_access
    not_found unless current_user.try(:staff?)
  end
end

app/views/stafftools/group_assignment_repos/_group_assignment_repo.html.erb
<div class="d-flex flex-md-row flex-items-center classroom-resource-item">
  <div class="col-1 d-flexp">
    <span class="group-assignment-icon assignment-icon-group left">
      <%= octicon 'repo' %>
    </span>
  </div>

  <div class="col-10 col-md-10 d-flex flex-column">
    <%= link_to stafftools_group_assignment_repo_path(group_assignment_repo.id) do %>
      <strong class="search-result-title"><%= t('views.stafftools.group_assignment_repos.group_assignment_title', title: group_assignment_repo.group_assignment_title) %></strong>
    <% end %>

    <span class="text-gray css-truncate css-truncate-target">Created <%= local_time_ago(group_assignment_repo.created_at) %></span>
  </div>
</div>

app/views/stafftools/group_assignment_repos/show.html.erb
<div class="site-content">
  <div class="d-flex flex-md-row flex-items-center stafftools-page-header">
    <div class="col-1">
      <span class="assignment-icon assignment-icon-group left">
        <%= octicon 'repo', height: 22 %>
      </span>
    </div>

    <div class="col-10 col-md-10 d-flex flex-column">
      <h2 class="stafftools-heading">
        <%= "#{t('views.stafftools.group_assignment_repos.group_assignment_repo')} #{@group_assignment_repo.id}" %>
      </h2>

      <p class="assignment-type text-gray"><%= t('views.stafftools.group_assignment_repos.group_assignment_repo_small') %></p>
    </div>
  </div>

  <div class="boxed-group">
    <h3>General information</h3>

    <div class="boxed-group-inner">
      <table>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.group_assignment_repos.id') %></td>
          <td><%= @group_assignment_repo.id %></td>
        </tr>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.group_assignment_repos.owned_by') %></td>
          <td><%= link_to @group_assignment_repo.organization.title, stafftools_organization_path(@group_assignment_repo.organization.id) %></td>
        </tr>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.group_assignment_repos.created_by') %></td>
          <td><%= link_to @group_assignment_repo.creator.github_user.login, stafftools_user_path(@group_assignment_repo.creator) %></td>
        </tr>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.group_assignment_repos.group_assignment') %></td>
          <td><%= link_to @group_assignment_repo.group_assignment.title, stafftools_group_assignment_path(@group_assignment_repo.group_assignment.id) %></td>
        </tr>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.group_assignment_repos.group') %></td>
          <td><%= link_to @group_assignment_repo.group.title, stafftools_group_path(@group_assignment_repo.group.id) %></td>
        </tr>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.group_assignment_repos.created_on') %></td>
          <td><%= local_time(@group_assignment_repo.created_at) %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="boxed-group">
    <h3><%= t('views.stafftools.group_assignment_repos.github_repo') %></h3>
    <div class="boxed-group-inner">
      <table>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.group_assignment_repos.repo_id') %></td>
          <td><%= @group_assignment_repo.github_repo_id %></td>
        </tr>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.group_assignment_repos.source_code') %></td>
          <td><%= link_to @group_assignment_repo.github_repository.html_url, @group_assignment_repo.github_repository.html_url %></td>
        </tr>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.group_assignment_repos.import_status') %></td>
          <td><%= @group_assignment_repo.import_status%></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="boxed-group dangerzone">
    <h3><%= t('views.stafftools.group_assignment_repos.dangerzone') %></h3>

    <div class="boxed-group-inner">
      <p>
        <a data-remodal-target="delete-group-assignment-repo" class="btn btn-danger"><%= t('views.stafftools.group_assignment_repos.delete_repo_title') %></a>
      </p>

      <div class="remodal text-left" data-remodal-id="delete-group-assignment-repo">
        <button data-remodal-action="close" class="remodal-close"><%= octicon 'x' %></button>
        <h2 class="remodal-header"><%= t('views.stafftools.group_assignment_repos.delete_repo_confirmation') %></h2>

        <div class="remodal-warning"><%= t('views.stafftools.group_assignment_repos.delete_repo_warning') %></div>

        <div class="remodal-description">
          <p><%= raw t('views.stafftools.group_assignment_repos.delete_repo_desc') %></p>
        </div>

        <%= form_for @group_assignment_repo, url: stafftools_group_assignment_repo_path(@group_assignment_repo), html: { "data-name" => @group_assignment_repo.id, method: 'delete' } do |f| %>
          <dl class="form js-normalize-submit">
            <dt><%= t('views.stafftools.group_assignment_repos.repo_id_confirmation', group_assignment_repo_id: @group_assignment_repo.id) %></dt>
            <dd><input type="text" class="js-input-block form-control input-contrast input-block" autofocus></dd>
          </dl>

          <%= f.submit t('views.stafftools.group_assignment_repos.delete_repo_link_text'), class: 'btn btn-danger btn-block js-submit', disabled: true %>
        <% end %>
      </div>
    </div>
  </div>
</div>